[operation]
num_cores = 6
threshold = 1.0e-8
debug = false

[results]
output_dir = "../outputs/ADRIA_results/HighResCoralStress"

[fig_fontsize]
fontsize = 6

[fig_formats_cm]
violin_width = 17
map_height = 18
map_width = 18
ecs_width = 10
ecs_height = 13
timeseries_width = 20
violin_height = 14
timeseries_height = 15
