[operation]
num_cores = 6
threshold = 1.0e-8
debug = false

[results]
output_dir = "../outputs/ADRIA_results/HighResCoralStress"

[fig_formats_cm] # Note that all figure sizes are input in cm, but fontsize matches word pt
map_width = 18
map_height = 18
ecs_width = 10
ecs_height = 13
timeseries_width = 18
timeseries_height = 13
violin_width = 17
violin_height = 14

[fig_fontsize]
fontsize = 6