[domain]
domain_dir = "../../ADRIA Domains/GBR_2024_10_15_HighResCoralStress/"

[operation]
num_cores = 6
threshold = 1.0e-8
debug = false

[results]
output_dir = "../outputs/ADRIA_results/HighResCoralStress"