---
title: Importance of depth refugia for reef resilience and intervention on the Great Barrier Reef under future climate change
author:
  - name: Benjamin Grier
    email: grierben777@gmail.com
    affiliations:
        - id: AIMS
          name: Australian Institute of Marine Science
          address: Townsville, Queensland, Australia
    attributes:
        corresponding: true
  - name: Takuya Iwanaga
    email: t.iwanaga@aims.gov.au
    affiliations:
        - id: AIMS
          name: Australian Institute of Marine Science
          address: Townsville, Queensland, Australia
  - name: Pedro Ribeiro De Almeida
    email: p.ribeirodealmeida@aims.gov.au
    affiliations:
        - id: AIMS
          name: Australian Institute of Marine Science
          address: Townsville, Queensland, Australia
  - name: Chinenye Ani
    email: c.ani@aims.gov.au
    affiliations:
        - id: AIMS
          name: Australian Institute of Marine Science
          address: Townsville, Queensland, Australia
  - name: Sam Matthews
    email: s.matthews@aims.gov.au
    affiliations:
        - id: AIMS
          name: Australian Institute of Marine Science
          address: Townsville, Queensland, Australia
abstract: |
    Coral reefs globally face unprecedented threats from climate change, with the Great 
    Barrier Reef (GBR) experiencing cumulative stressors and increasingly severe declines 
    in coral cover from thermal stress events. Understanding drivers behind reef resilience 
    to climate impacts is critical for conservation planning and intervention strategies. A 
    scenario-based population modelling approach was adopted with larval connectivity dynamics, 
    thermal adaptation, and environmental factors to assess coral reef resilience across GBR 
    locations under future climate projections. Using five Global Climate Models (GCMs) 
    spanning five Equilibrium Climate Sensitivities,  reefs were analysed for coral cover 
    time series and their ability of reefs to maintain positive carbonate production budgets 
    under future conditions. Contrary to expectations, larval connectivity patterns did not 
    correlate with increases in maintenance of positive carbonate budgets. Instead, reef depth 
    emerged as the primary predictor of cover-time series resilience and maintenance of positive 
    carbonate budgets, with deeper reefs benefiting from thermal refugia that reduce bleaching 
    impacts. These findings suggest that depth provides critical 
    protection against thermal stress, contrasting current intervention practices that primarily target easily 
    accessible sites in the 1-10m depth range. These results have important implications 
    for reef management, indicating that depth refugia should be prioritized for further 
    consideration in conservation planning alongside connectivity modelling advancements 
    to maximize coral survival under continuing climate change. 
keywords:
  - Coral reef
  - Climate change
  - Ecosystem resilience
  - Reef depth
  - Reef connectivity
date: last-modified
format:
  elsevier-docx:
    journal:
      name: Journal Name
      formatting: preprint
      cite-style: authoryear
bibliography: references.bib
engine: julia
crossref:
  custom:
  - kind: float
    reference-prefix: SFigure
    key: sfig
  - kind: float
    reference-prefix: STable
    key: stbl
editor:
  markdown:
    wrap: 92
    canonical: true
---

# Introduction

Climate change is impacting species survival, persistence and ecosystem functions on coral
reefs, which are vulnerable to increasing magnitude and variation in environmental stressors
such as ocean temperature [@foster2021; @gattuso2014]. Mass bleaching and associated
mortality events driven by climate change can cause reef-building coral population declines
[@hughes2017; @hughes2018; @bozec2025], possibly leading to coral-macroalgae regime shifts
[@arif2022; @wild2011]. Climate impacts on coral reefs are decreasing the ability of coral
reefs to provide ecological functions such as benthic habitat and nutrient cycling
[@forster2021; @williams2019] and services such as food, protection, tourism and Indigenous
cultural value [@eddy2021; @stoeckl2021].

Coral reef ecosystem resilience - the capacity to maintain coral populations and avoid
ecosystem regime shifts - is conceptualised to depend on three interconnected mechanisms.
First, the ability of individual corals to survive thermal stress. Second, the connectivity
networks that enable recolonisation after disturbances [@hock2017; @mumby2008; @torres2024].
Third, the maintenance, and accretion, of the carbonate framework that provides reef
structure [@perry2012]. This investigation aims to assess how these mechanisms interact
under projected climate conditions to identify the characteristics of resilient reefs in the
Great Barrier Reef (GBR) ecosystem.

The GBR is the world's largest coral reef ecosystem consisting of thousands of individual
reefs interconnected through larval dispersal patterns mediated by hydrodynamic, spatial,
and ecological processes [@cappo2000]. The GBR faces severe projected coral cover declines
under climate change [@bozec2025; @bozec2022; @condie2021]. Coral cover declines will be
compounded by ocean acidification, tropical cyclones, and crown-of-thorns starfish outbreaks
[@death2012; @fox-kemper2021; @seneviratne2021; @sweatman2011; @wolff2018]. The 2023-24
Summer mass bleaching event may be signalling a shift towards this reef future, with some
level of bleaching recorded on 79% of surveyed reefs (total 1001 surveyed reefs)
[@australianinstituteofmarinescience2024; @cantin2024].

At the individual coral scale, survival during thermal stress events depends on both
environmental and biological factors that can either amplify or reduce thermal stress. Depth
is a crucial factor that can provide a refuge from thermal stress [@álvarez-noriega2018;
@baird2018; @smith2014]. Biological factors including coral size [@brandt2009], taxa
[@álvarez-noriega2018; @mcclanahan2005], and thermal tolerance through acclimation and
inheritance [@humanes2022; @lachs2024] all influence survival outcomes. Corals demonstrate
adaptive capacity to develop thermal tolerance that could delay widespread bleaching under
moderate emission scenarios [@bairos-novak2021; @humanes2022], representing a crucial
mechanism for reef persistence.

Beyond individual survival, reef-scale resilience depends on connectivity networks that
enable recolonization after disturbances [@angeler2023; @elmhirst2009; @hock2017]. Larval
source populations that export more larvae than they import are essential for system-wide
recovery, providing larvae that enable recolonization at distant locations [@hock2017;
@thomas2015]. Yet these source reefs are paradoxically more vulnerable individually, relying
heavily on local recruitment for their own recovery. When disturbances impact major source
populations, cascading effects reduce larval export and slow recovery throughout the
connected network [@figueiredo2022; @hock2017; @munday2009].

Long-term reef viability requires not only coral survival and recolonization, but also
maintenance of physical reef structures through positive carbonate budgets. Scleractinian
corals build the primary habitat framework, but reef persistence depends on the balance
between carbonate accumulation [@perry2015] and loss through bioerosion, physical damage
[@kenyon2023], and dissolution [@eyre2014; @eyre2018]. This balance is influenced by coral
cover and community complexity [@perry2012; @desbiens2021], environmental processes, and
ocean chemistry [@perry2015; @eyre2018].

Recent advances in whole-ecosystem larval connectivity modelling [@choukroun2025] and coral
thermal response research [@bairos-novak2021] enable integrated investigation of how
multiple factors interact to determine climate resilience. By incorporating the latest coral
population models [@ribeirodealmeida2024], ecosystem-wide connectivity data, and updated
climate projections [@dixon2022], we can examine which factors most strongly influence reef
persistence under different scenarios. While connectivity has been emphasized as critical
for GBR resilience [@hock2017], and remains an important consideration, integrated modelling
reveals depth plays a fundamental role for maintenance of reef coral populations and
positive carbonate budgets under current projections of climate change.

# Methods

## Reef definitions

The spatial extent of reefs represented in this investigation follows reef definitions
available via the Great Barrier Reef Marine Park Authority (GBRMPA). Reef definitions
outline 3806 reefs across the GBR [@GBRMPA2022] (@fig-region-map). Prior analyses by Bozec
et al. [-@bozec2022] provided estimates of coral carrying capacity for each reef that were
adopted by this study.

Depths for each reef were extracted using 10m resolution bathymetry data made available in
GBRMPA [-@GBRMPA2020]. While the bathymetry data are said to be accurate up to 15m from Mean
Sea Level [@GBRMPA2020], there are many sources of uncertainty in the depth estimates used
for this study. Notably, bathymetry data were derived from satellite imagery. The bathymetry
data can be limited in their alignment with the established GBRMPA reef outlines used to
characterise reef locations and their areal extent. For each reef, bathymetry data were
spatially matched with the 3806 reef outlines through geometric intersections. All depth
values were converted to positive values (depths below sea level). The median depth was used
to provide an indicative depth value for each reef. Further limitations are outlined in the
Discussion. Code to extract depth estimates, and the resulting depth estimates themselves,
are available at [@iwanaga2025].

A Quality Assessment and Control process identified reefs with potential data limitations:
reefs with no overlapping bathymetry data, reefs with minimum depth values above sea level
(indicating potential data artifacts), and reefs where bathymetry pixels covered less than
5% of the reef polygon area. This process removed 842 reefs, or 22%, from the initial set of
3806 reefs. Furthermore, reefs that are not associated with GBRMPA Management areas
[@GBRMPA2007] or reefal bioregions [@GBRMPA2024] were removed. Bioregions which contained
fewer than three reefs after these processes were also excluded. As a result, 1377 reefs
were excluded, leaving a total of 2429 remaining for time series clustering. To ensure
effective data analysis, reefs with incoming or outgoing connectivity values below the 5th
percentile were removed from post-hoc analyses, leaving 2197 reefs remaining for display in
results (@fig-region-map).

![Map of the Great Barrier Reef region, including GBRMPA Management areas (polygons) and all
considered reefs (points). Colour-coded polygons outline GBR marine park management regions:
Far Northern (orange), Cairns-Cooktown (green), Townsville-Whitsunday (blue) and
Mackay-Capricorn (red) [@GBRMPA2007]. Reef centroids are marked individually for visual
clarity and are coloured by bioregions [@GBRMPA2024]. All 2197 reefs included in this
investigation are represented in this figure. Annotations represent major coastal
settlements along the GBR.](../figs/region_map.png){#fig-region-map fig-align="center"
width="14.8cm"}

## Degree Heating Week trajectories

Future projections of maximum yearly Degree Heating Weeks (DHWs) for each reef were
estimated from Sea Surface Temperature (SST) data for the GBR. Statistically downscaled
1km^2^ resolution SST data for five Global Climate Models (GCMs) were obtained from the
HighResCoralStress database [@dixon2022; @dixon2023]. These five GCMs were EC-Earth3-Veg,
ACCESS-CM2, ACCESS-ESM1-5, NorESM2-MM and GFDL-CM4. The selected GCMs are a part of the
Sixth Phase of the Coupled Model Intercomparison Project (CMIP6), spanning four 'model
development families' as defined by Brunner et al., [-@brunner2020]. Shared Socio-economic
Pathway (SSP) 2-4.5 was used to represent the plausible emission pathway. It represents a
moderate emissions scenario with continued CO~2~ emissions comparable to present day until
2050, after which emissions gradually decline [@hausfather2020; IPCC -@climate2023].

These GCMs were selected based on evaluation by Grose et al., [-@grose2023], indicating
their ability to recreate historical atmospheric temperature and precipitation conditions in
the Australasian region. They span a range of Equilibrium Climate Sensitivity (ECS) values
within the Intergovernmental Panel on Climate Change (IPCC) assessed likely range. The IPCC
defines ECS as the long-term warming caused by a doubling of carbon dioxide above its
pre-industrial concentration [@forster2021]. While Grose et al. [-@grose2023] do not
consider oceanic data, they provide a region-specific selection mechanism which is used as
an indicator of general performance of GCMs for the region. An overview of the selected GCMs
is provided in @tbl-gcms. Note here that Grose et al., [-@grose2023] assessed GFDL-ESM4,
whereas Dixon et al., [-@dixon2022; -@dixon2023] provides data based on GFDL-CM4. This
substitution is assumed appropriate given they share the same fundamental representation of
the physical climate system. The use of these GCMs therefore allows for a range of possible
futures to be explored, capturing uncertainty in future responses to CO~2~ increases
(@fig-methods-dhws; @sfig-ecs;[@grose2023; @shepherd2018]) and enables the assessment of
modelled coral reef behaviour over a broad range of independently derived climate futures
[@abramowitz2019; @brunner2020].

Daily SST data [@dixon2023] were used to calculate climatological baselines and “HotSpot
Anomaly” values for each pixel following NOAA methodology [@liu2017; @skirving2020].
Additional information about DHW calculation methods is provided in the supplemental
material. DHW values on a per-pixel basis at 1km^2^ resolution were calculated as the
12-week rolling sum of HotSpot SST Anomaly values that are greater than 1°C, expressed in
units of °C-weeks. The 12-week accumulation period reflects the cumulative nature of coral
thermal stress. Brief temperature spikes may be tolerable, but sustained or repeated
exposure to elevated temperatures causes progressively greater physiological stress and
bleaching severity. DHW values integrate both the magnitude and duration of thermal stress:
a moderate anomaly (e.g., 1°C) sustained for 12 weeks produces the same DHW value as a
severe anomaly (e.g., 3°C) lasting 4 weeks, though the biological impacts may differ. DHW
estimates for each indicative reef (see @GBRMPA2022) were then determined by taking the mean
DHW value for all pixels touching each reef outline. The process described here was
conducted for all 2197 reefs to create DHW projections spanning from 2025 to 2075.

::: {#tbl-gcms}
| Global Climate Model source | ECS value (°C)     | Interpreted relative severity | Results found in |
|-----------------------|-----------------------|------------------------|-----------------------|
| ACCESS-CM2                  | 4.66 [@grose2023]  | High                          | [@grier2025]     |
| EC-Earth3-Veg               | 4.30 [@wyser2020]  | High                          | [@grier2025]     |
| GFDL-CM4                    | 4.1 [@sentman2025] | High                          | [@grier2025]     |
| ACCESS-ESM1-5               | 3.87 [@ziehn2020]  | Intermediate                  | Main text        |
| NorESM2-MM                  | 2.5 [@seland2020]  | Low                           | [@grier2025]     |

Information for each GCM used in this investigation including Equilibrium Climate
Sensitivity (ECS) value, interpreted relative severity and where results for an individual
GCM results are found. GCMs in context with assessed plausible ranges of ECS values are
displayed in [@sfig-ecs]. ACCESS-ESM1-5 has an ECS closest to the midpoint of the likely ECS
range and was taken as an intermediate model with results displayed in the main text.
:::

![Degree Heating Week time series (in °C - Weeks) for the GCMs selected. Colours represent
the different Management areas across the Great Barrier Reef: Far Northern (orange),
Cairns-Cooktown (green), Townsville-Whitsunday (blue) and Mackay-Capricorn (red). Solid
lines represent management-area median time series and bands represent 95th percentile
confidence intervals.](../figs/methods_dhw_timeseries.png){#fig-methods-dhws
fig-align="center" width="14.82cm"}

## Assessment framework

An exploratory scenario modelling approach was adopted for this investigation. The method
involves exploring a wide range of potential futures and model parameterisations under
different assumptions of climatic and ecological conditions. Exploratory modelling
approaches have gained favour in recent years to explore the implications of deep
uncertainty; where there is little or no agreement on the key drivers of a system, the
extent of the relationship, how best to represent them or their probability distributions
[@conradt2024; @lempert2013]. The approach embraces uncertainty as an inherent
characteristic of complex environmental systems [@lempert2010; @lempert2013] to address
limitations of calibrated ecosystem models that use a singular set of parameter values
[@lubianabotelho2025]. Exploratory scenario modelling is a core methodology underpinning the
development of robust and adaptive management strategies [@haasnoot2013].

All data preparation, modelling and analyses were performed using the Julia programming
language [@bezanson2017], with visualisations created using the Makie plotting ecosystem
[@danisch2021]. Code used to process DHW data and perform analyses involved in this
investigation can be found at Grier and Iwanaga [-@grier2025].

### Connectivity modelling

The coral larval connectivity model used in this study comprises 3D hourly velocities from
the 1 km grid resolution hydrodynamic model [GBR-1 version 2.0; @steven2019], as input to
OceanParcels [@delandmeter2019], a particle tracking model. The connectivity model was used
to simulate larval dispersal and settlement of broadcast-spawning Acropora corals in the
GBR, following annual mass spawning events in 2015, 2016, 2018, 2019 and split-spawning
events in 2017 and 2020. Split spawning occurs when the annual reproductive event of a coral
population is split over two consecutive months. Coral mass spawning usually occurs 4-6 days
after the full moon during the spring-summer transition in the GBR with variations across
species and locations. The spawning days identified are: 2015 - November 30, December 1 and
2; 2016 - November 18, 19 and 20; 2017 - November 8, 9 and 10, December 8, 9 and 10; 2018 –
November 18, 19, 20; 2019 – November 16, 17, 18; 2020 – November 5, 6 and 7, December 4, 5,
6.  

For each spawning night, particles were released from random locations within each reef
polygon as neutrally buoyant virtual larvae every 27 seconds from 8:00 pm to 11:00 pm at
2.25 m below the surface. In each of the reef polygons, 401 particles were released
resulting in a total of 1,526,206 particles every night of spawning. The model was run for
30 days with a 3-minute timestep, and the locations of the released particles were updated
every 15 minutes until the end of the simulation. Larvae were assumed to become competent to
settle from 4 to 28 days post release with a daily mortality rate of 0.4 [@ani2024], which
was implemented in 15-minute timestep as probabilistic mortality, corresponding to 0.0053
mortality rate per timestep. To incorporate the stochastic sensory behaviour of larvae
during settlement, a 0.01 probability of settlement is assumed when larvae are over a reef
during the competency period per 15-minute timestep. The information obtained on larvae
settlement was used to compute a connectivity matrix among reef polygons for each spawning
night (see Ani et al. [-@ani2024] for more details). A total of 24 connectivity matrices
were generated for the spawning nights that were considered.

Larval transition matrices indicate the probability of larval transfer between pairs of
reefs in the GBR, herein referred to as connectivity strengths. Indicative connectivity
strengths are implemented in ADRIA-CoralBlox (described in the next section) as the mean of
matrices for each location (i.e., mean of all 24 spawning days). While the connectivity
strengths do not vary temporally within each ADRIA-CoralBlox simulation, spatial variability
enables investigations into the influence of connectivity strength and its role in driving
recovery processes.

To assess the impact of reef connectivity on modelled outcomes, connectivity was summarised
by incoming connectivity (weighted incoming connectivity), outgoing connectivity (outgoing
connection strength), the ratio of source-to-sink connectivity, and larval retention
probability for each reef. Weighted incoming connectivity was calculated by summing the
product of each connection strength incoming to a target reef (excluding retained larvae
from the target reef) and the mean timeseries absolute coral cover (km^2^) of each matching
source reef. This metric provides an approximation of overall larval flow into a reef, with
high values indicating the target reef is supplied high volumes of larvae via strong
connections and low values indicating the target reef has weak (or no) incoming connections
or is supplied by small source populations. A limitation of weighted incoming connectivity
is that it does not incorporate the proportion of the source reef's population that is
reproducing and producing larvae, instead it takes total coral cover area as an indicator of
larval productivity.

Outgoing connection strength was calculated as the sum of all outgoing transition
probabilities from a target reef. Outgoing connection strength has a theoretical maximum of
one (all larvae reach settlement on sink reefs), however the large size of the GBR combined
with larval mortality result in much lower outgoing connection strength values. The ratio of
source-to-sink connectivity ($O:I$) for a target reef represents the strength of the reef's
outgoing larval flow relative to it's incoming larval flow. This is calculated as:
$O:I = \frac{S_O/N_O}{S_I/N_I}$. Where $S$ represents the sum of connectivity probabilities,
$N$ represents the number of connections, $O$ denotes outgoing connectivity from the target
reef and $I$ denotes incoming connectivity to the target reef. If a reef has no incoming
connections, the $O:I$ equals the $S_O/N_O$ value. Incoming connections in this calculation,
do not directly represent the larval supply gained as the breeding populations from which
connections are coming from are not represented. A source-to-sink ratio greater than 1 (a
value greater than 0 on a log scale) indicates a reef has greater outgoing than incoming
larval flow. Reef larval retention probability indicates the proportion of spawned larvae
that settle on their natal reefs.

### Scenario modelling

Two systems were employed to explore scenarios: ADRIA (the Adaptive Dynamic Reef
Intervention Algorithms platform) and CoralBlox, referred to as the coupled framework
ADRIA-CoralBlox. ADRIA is a multi-criteria decision support platform designed for the
assessment and analysis of coral reef intervention strategies under uncertainty
[@iwanaga2023]. The ADRIA platform provides functionality for scenario generation and
analysis as well as providing technical infrastructure to couple environmental and ecosystem
representations. CoralBlox is a computationally efficient coral population model. It
simulates functional/morphological groups of corals over their life cycles, competing for
available space over time [@ribeirodealmeida2024].

The coral demographic representation and associated model implementation are further
detailed in the supplementary material. Of note is that the representation of bleaching
mortalities followed Bozec et al., [-@bozec2022] and Baird et al. [-@baird2018] which
applies a scaling coefficient to incorporate the amelioration effect that depth may have.
This depth-scaling reduces the proportion of coral colonies impacted by high heat stress as
depth increases. The impacts of tropical cyclones, wave activity, Crown of Thorns Starfish
or coral disease were not included in this investigation in order to focus on assessing reef
resilience under possible future warming scenarios.

ADRIA-CoralBlox was run for 4096 scenarios for each GCM (20,480 total model runs). Here, a
scenario represents a unique combination of assumed environmental (namely one of the five
DHW trajectories) and ecological factors including coral growth and mortality rates, and
coral thermal tolerances. Scenarios were generated using the low-discrepancy Sobol' sampling
method [@sobol1967; @sobol1993] with Owen Scrambling [@owen1995], a randomised Quasi Monte
Carlo approach which balances scenario exploration with improved convergence properties
compared to pseudo-random sampling. A detailed comparative analysis of sampling methods can
be found in [@lecuyer2018; @kucherenko2015]. For scenario assessment, coral cover time
series for each model run were scaled to represent cover as a percentage of the total
estimated reef area. The scenario-median time series for each reef was used for further
analyses. Time series of coral cover were then clustered based on their behaviour.
Assessment metrics used in analyses can be found in @stbl-metrics.

### Time series clustering

Reefs were clustered based on the behaviour of their median coral cover time series. Put
simply, reefs that have similar trends and trajectories are more likely to be clustered
together. Reefs are clustered into Low, Medium, or High, indicating their relative ability
to maintain coral cover over time. Reefs in each time series cluster were compared to
identify characteristics that differ between Low, Medium and High clusters. These
characteristics include reef median depth, mean time series DHW, weighted incoming
connectivity, outgoing connection strength, ratio of source-to-sink larval connectivity,
larval retention probability and reef carrying capacity (coral habitable area).

The Complexity-Invariant Distance (CID) between each time series was calculated to identify
similarities in temporal behaviour [@batista2014]. The CID applies a correction factor to
the Euclidean distance between pairs of time series to obtain a measure of their similarity.
The adopted approach ensures reefs are clustered based on their temporal dynamics as opposed
to, for example, naively clustering by their mean coral cover. Time series clustering is
achieved using k-medoids clustering [cf. @steinmann2020]. Further details on the time series
clustering approach are found in the supplementary materials.

Time series clustering was applied over the time frame between 2025 and 2075. The clustering
was conducted at three spatial scales: (1) the whole of GBR; (2) each GBR management area;
and (3) for each reefal bioregion (defined in GBRMPA [-@GBRMPA2024]). Analyses were
conducted at the different spatial scales as, conceptually, the temporal behaviour
constituting "low", "medium" or "high" coral cover may differ at different spatial scales.
Analyses at the whole-of-GBR scale were found to lead to identical conclusions regarding
reef characteristics which influence coral cover and so for brevity are not shown here.

To compare time series clustering results across GCMs, management area scale clustering
results are used to preserve coarse scale latitudinal differences between regions, while
maintaining ease of comparison and visualisation. These comparisons include quantification
of differences between low and high cover clusters across management regions under each GCM
using the CID between cluster median time series. To assess how different reef
characteristics influence time series clustering at a finer spatial scale, bioregion results
are used to capture patterns occurring within individual groups of reefs. Results of all
analyses at all spatial scales can be found at Grier and Iwanaga [-@grier2025] for those
interested.

#### Partial Dependence Analysis

Partial Dependence Analysis (PDA) was conducted to understand relationships between features
and bioregion-scale time series cluster predictions using a Random Forest (RF) classifier
[@friedman2001]. The analysis utilised the reef characteristics of interest as the
predictors, including the estimated median reef depth, mean DHW for the given GCM,
log10-weighted incoming connectivity, outgoing connectivity, and log10-transformed
outgoing-to-incoming connectivity ratio. Conceptually, PDA is related to a Regional
Sensitivity Analysis [@hornberger1981; @pianosi2016], as model results are assessed to map
the influence of $X$ - the predictors or model factors - on $y$ - the modelled outcomes
according to a metric of interest.

The full dataset consisted of the time series cluster assignment for each of the 2197 reefs
under the each GCM (totalling 10,985 samples). The dataset was randomly split into training
(60%) and testing (40%) subsets to train and assess classification performance. The RF
classifier achieved 80% accuracy on the training set and 60% on the test set. A 3-fold
cross-validation was also conducted, arriving at a similar 59% accuracy rate. F1 performance
scores for Low, Medium, and High clusters were determined to be 0.70, 0.43 and 0.64
respectively, with precision of 0.62, 0.51 and 0.66 when evaluated with the test set
(consisting of 4394 samples) (@stbl-confusion-matrix; @stbl-rf-cluster-performance). Lower
performance with the Medium cluster reflects the inherent difficulty of classifying
transitional states in natural systems. The consistent level of accuracy across test and
cross-validation demonstrates the generalised performance of the RF classifier, while not
accurate, is still sufficiently informative for the purpose of assessing the influence of
reef characteristics.

Partial dependence analysis was performed by applying the trained model to the test dataset.
Values for individual predictors were systematically varied (one-at-a-time) across a grid of
50 equally spaced points spanning the predictor's range, while all other features were left
at their modelled values. The procedure creates (1) a modified test dataset, where the
target predictor was set to the grid value for all samples, (2) probabilistic predictions
for all three cluster classes using the trained RF classifier, and (3) the mean predicted
probability for each class across all test observations. The process isolates the marginal
effect of each predictor by averaging over the natural distribution of all other
representative reef characteristics in the test dataset. Additionally, to assess possible
interaction between reef depth and connectivity metrics, two-way PDA was performed on grids
along the ranges of depth and weighted incoming connectivity, and depth and outgoing
connection strength.

### Carbonate budget analysis

Using coral cover time series for each reef, the number of years each reef maintains coral
cover above a given percent threshold were calculated. The threshold represents the level of
live coral cover necessary to maintain a positive carbonate budget (denoted here as
$\theta_{0}$ to indicate the budget equilibrium). A greater number of years above
$\theta_{0}$ suggests greater resilience and opportunity for recovery.

Recent analyses suggest a general threshold of \~17% live coral cover in the case of the
mid-shelf and offshore GBR reefs [@desbiens2021]. Given in-situ carbonate budgets are
influenced by (1) a range of processes; (2) the variety of approaches that could be used to
measure those processes; and (3) the uncertainty surrounding these, it would be unreasonable
to assume all reefs adhere to a single precise $\theta_{0}$ value. Concurrently, it is
difficult to ascertain a suitable $\theta_{0}$ value for each individual reef.

Given the uncertainties present, the proportion of modelled reefs that display capacity to
maintain coral cover above a given $\theta_{0}$ threshold is examined. An indicative range
of 10 to 20% is used (inclusive, with a step size of 1%). The range was informed by Perry et
al., [-@perry2015] and Desbians et al., [-@desbiens2021] providing plausible indications of
the lower and upper bounds respectively. Robustness of the conclusions drawn to the
uncertainty in the precise value of $\theta_{0}$ for all reefs can then be assessed by using
the indicative range.

The relationships between the number of years above $\theta_{0}$ and characteristics such as
median reef depth and log10 total connectivity strength were assessed with Spearman's rank
correlation. Spearman's correlation was adopted as distributions of reef depths and number
of years above $\theta_{0}$ were expected to be non-normal and highly skewed. Furthermore,
reefs are naturally of different types and experience different conditions, and so the
monotonic trends (whether the relationship consistently increase or decrease) rather than
the exact quantitative relationship was of interest.

# Results

## Reef trajectories across futures

There were substantial differences in the maintenance of coral cover post 2030 between the
GCMs (@fig-gcm-cover-trajectories). Of the GCMs explored, NorESM2-MM had the lowest ECS
(2.5°C) and reefs exhibit continuing recovery and decline dynamics up to 2075 under this
hypothetical climate future. Unsurprisingly, recovery phases were predominantly seen in the
reefs in the High cover cluster, with Medium and Low exhibiting lesser probability of such
periods of recovery. Generally, recovery and increases in coral cover were visible in
simulated results up to 2045. Under NorESM2-MM, the Far Northern Management area was found
to have the most similar temporal behaviour between Low and High clusters compared to other
Management areas (@stbl-cluster-cid) due to the low degree of coral cover overall
(@fig-gcm-cover-trajectories).

Intermediate levels of coral cover maintenance can be seen in ACCESS-ESM1-5 (ECS value of
3.87°C) when compared to the other GCMs (of higher and lower ECS values). Under these
intermediate conditions (in relative terms), there is potential for reefs in the High
cluster to maintain coral cover levels around 20% to 2050. The highest peak DHW levels occur
under GFDL-CM4 between 2045 and 2050, while greater increases in overall DHWs time series
occur under ACCESS-CM2 (@fig-methods-dhws). Under conditions represented by high ECS value
GCMs - specifically, ACCESS-CM2 (4.66°C), EC-Earth3-Veg (4.30°C) and GFDL-CM4 (4.1°C) - all
reefs are largely in decline across all management areas from 2035 (@stbl-cluster-cid).

![Time series of coral cover (relative to reef area) clustered within each Management area
(rows), for each GCM analysed (columns) based on temporal behaviour over 2030 and 2060. Time
series were clustered into "Low" (green), "Medium" (orange), and "High" (blue) clusters
indicating their relative median coral cover. Solid lines represent cluster median time
series and bands represent 95th percentile confidence
intervals.](../figs/GCM_cover_timeseries_plot.png){#fig-gcm-cover-trajectories
fig-align="center" width="14.82cm"}

Comparing across GCMs, it is common for reefs to switch between clusters, including from Low
to High and vice versa (@sfig-gcm-bioregion-cluster-assignment). Of 2197 reefs, 21% (462) of
reefs have consistent cluster assignment across all GCMs. Of the 462 consistently assigned
reefs, 23% are within the Far Northern Management area, with 1%, 55% and 21% occurring in
Cairns-Cooktown, Townsville-Whitsunday and Mackay-Capricorn Management areas respectively
(@sfig-gcm-cluster-map). Of the 462 consistently assigned reefs, 34%, 18% and 47% are
clustered into Low, Medium and High clusters respectively. High levels of assignment
variability across GCMs are expected as due to spatial differences in each given GCM’s DHW
trajectories.

### Bioregion scale clustering

Relationships between reef characteristics and bioregion-scale time series clusters were
found to be similar across GCMs. Across bioregions, reefs in the High cluster not only had
greater levels of coral recovery but displayed persistence to 2050
(@sfig-access-esm1-5-bioregion-timeseries). Qualitative representations of bioregion scale
clustering results across assessed reef characteristics can be found in the supplementary
material, with Partial Dependence Analysis results displayed in the main text.

#### Partial dependence

Partial Dependence Analysis revealed reef median depth, carrying capacity and mean time
series DHW level have the highest feature importance scores, accounting for 29%, 15% and 15%
predictive importance respectively (@fig-ts-cluster-pdp; Panel A). Source-cover weighted
incoming connectivity, outgoing connectivity strength, source-to-sink connectivity ratio and
larval retention probability account for \~12%, 11%, 10% and 8% respectively.

Reefs have the greatest probability of being clustered into Low if shallow, and High at
greater depths, with medium cluster reefs exhibiting a lower, and more stable, assignment
probability across depth ranges (@fig-ts-cluster-pdp; Panel B). A large increase in the
probability of a reef being categorised as High can be seen between 10 and 15 meters depth.
This is at the edge of the depth range used in current deployment efforts [@howlett2021;
@randall2021; @whitman2024] but indicates a depth range that could be adopted to maximise
longevity and benefits of, for example, coral seeding activities. Across mean DHW values,
assignment probability is roughly equal across the three clusters up to 5 DHW. A sharp
delineation can be seen \> 5 DHW when comparing High with other clusters, with lower
assignment probability (\~25%) compared to Medium and Low (\~40%) (@fig-ts-cluster-pdp;
Panel B).

![Feature importance scores (Panel A) of the Random Forest classifier, and Partial
Dependence Plots (PDPs) for reef characteristics of interest indicating the probability of a
reef being classified to one of the three cover clusters (Panel B). PDPs indicate the
probability of a reef from the test dataset being clustered into each cover cluster
depending on the predictor value on the x axis, when adjusted for values of other
predictors. Green, orange and blue lines indicate cluster assignment probability for Low,
Medium and High clusters respectively. Transparent grey points above probability lines
represent predictor values present in the test dataset, providing a rough indication of
predictor value distribution across assessed
reefs.](../figs/ts_cluster_rf_feature_analysis.png){#fig-ts-cluster-pdp fig-align="center"
width="14.82cm"}

First-order PDA showed minimal influence of incoming, outgoing and source-to-sink ratio
connectivity metrics on cluster assignment probabilities. Two-way analyses revealed little
interaction between depth and incoming and outgoing connectivity metrics for reef clustering
probabilities (@fig-ts-cluster-pdp-twoway-incoming; @sfig-ts-cluster-pdp-twoway-outgoing).
Reefs with a median depth around 15m and high incoming connectivity may benefit slightly,
with higher probability of High cover cluster assignment compared to 15m - depth reefs with
lower connectivity.

![Partial Dependence Plot indicating the estimated probability (via Random Forest
classification) of cluster assignment along interacting values of median reef depth (meters)
and log10-weighted incoming connectivity. Colour (ranging from dark purple to yellow)
indicates the probability of assignment to each cluster, with brighter shades indicating
higher probability of assignment. Panels A, B, and C illustrates the assignment probability
for Low, Medium, and High cover clusters respectively. The distribution of reef depth and
incoming connectivity values are shown in Panels D and
E.](../figs/ts_cluster_rf_twoway_depth_incomingconn_pdp.png){#fig-ts-cluster-pdp-twoway-incoming
fig-align="center" width="14.82cm"}

Individual feature analysis for carrying capacity indicates that its influence on cluster
assignment is concentrated at the low range of predictor values (@fig-ts-cluster-pdp). This
aligns with the right-skewed distribution of carrying capacity across reefs for these three
predictor variables. Beyond this low-end range, partial dependence becomes near constant,
indicating outlier values for these factors are not influential. Assessing random forest
prediction accuracy across bioregions reveals increasing performance as mean bioregion reef
depth increases (@sfig-rf-predictor-perf). Unexplained variation in the test dataset (33% of
variation) may be concentrated in shallow bioregions where considered model predictors do
not capture differences between clustered reefs.

## Reef carbonate budget

Reef median depth had a moderate positive correlation with the number of years a reef
maintains coral cover above the assumed carbonate budget threshold required to sustain live
coral cover ($\theta_{0}$). Greater median depth was a key characteristic defining reefs
that sustain coral cover above $\theta_{0}$ (@fig-access-esm1-5-depth-conn-carbonate;
@sfig-access-esm1-5-carb-budget-corr; @sfig-access-esm1-5-mean-carb-budget). Unsurprisingly,
the number of years above $\theta_0$ substantially decreased as $\theta_0$ is increased, as
does the Spearman's correlation (@sfig-access-esm1-5-carb-budget-corr). Decreasing
correlation levels are likely due to an increasing number of reefs being unable to maintain
coral cover above $\theta_0$ as it is increased, with the distribution of years above
threshold becoming increasingly right-skewed (@fig-access-esm1-5-depth-conn-carbonate). In
contrast, weighted incoming connectivity strength (log10 scale) was found to have no
correlation with the number of years a reef maintains cover above the required thresholds
(@sfig-access-esm1-5-carb-budget-corr).

![Number of years reef coral cover exceeds the assumed carbonate budget threshold in terms
of coral cover ($\theta_0$) between 2025 to 2075 (y-axis) under ACCESS-ESM1-5. Left panel
shows the relationship between reef median depth, while the right panel shows the same for
log10-weighted incoming connectivity. Point colour (purple to yellow) represents
($\theta_0$), with brighter shades indicating a higher $\theta_0$. Deeper reefs have an
increased number of years above the considered range of $\theta_0$, while no relationship
between weighted incoming connectivity and carbonate budget maintenance was
found.](../figs/ACCESS-ESM1-5/depth_conn_carbonate_comparison.png){#fig-access-esm1-5-depth-conn-carbonate
fig-align="center" width="14.82cm"}

# Discussion

Results show increasing reef depth has a strong positive impact on modelled reef resilience
in temporal behaviour and maintenance of positive carbonate budgets under possible future
conditions. Reefs with a median depth of 10m or greater, with high incoming connectivity,
are the most likely to be assigned to a high cover time series cluster. By itself, incoming
connectivity alone does not correlate with maintenance of positive carbonate budgets. These
findings highlight the importance of depth and incoming connectivity as coupled selection
features when assessing potential reef resilience under future thermal stress.

Reefs in different temporal clusters largely do not differ in mean modelled DHW levels
experienced and exhibit overall similar DHW time series. While reefs experience similar
magnitude DHWs based on SST, the proportion of a reefs' coral population impacted by heat
stress events depends on reef depth. Results of this investigation suggest that for
non-mesophotic reef ecosystems (i.e., \< 30m), depth contributes greatly to reef resilience
and maintenance positive carbonate budgets under future conditions.

Movement of shallow reefs towards negative carbonate budgets in the future may contribute to
phase shifts in dominant sources of CaCO~3~ production. Reefs may switch away from
coral-driven processes, and CaCO~3~ accretion, to encrusting algae driven CaCO~3~
production, or to bioerosion dominated systems with rapid erosion of physical reef
frameworks [@dudgeon2010; @perry2008]. Reefs at increased depths may be able to maintain
coral driven CaCO~3~ production and accumulation into the future for longer.

Spatially these results indicate that regions of positive carbonate budget maintenance,
under ACCESS-ESM1-5, and high depth levels were concentrated in the Far Northern, offshore
Townsville/Whitsunday, and Mackay/Capricorn management areas (@sfig-depth-map;
@sfig-carb-budget-map). Resilient reefs in the Far Northern management area were exposed to
lower mean DHW levels than other reefs under ACCESS-ESM1-5 (@sfig-mean-dhw-map), however
similar spatial patterns were observed across GCMs for reefs clustered into the high cover
cluster (@sfig-gcm-cluster-map).

These findings are not to be interpreted as accurate predictions of future resilience due to
high uncertainty in input data, particularly depth and connectivity. While similar findings
have been demonstrated in the Pacific [@smith2014; @baird2018] and Indo-Pacific
[@bridge2014] regions, depth refugia analyses have often focused on the potential of
mesophotic reefs (\> 30m deep) as thermal refugia [@bongaerts2010; @holstein2015;
@semmler2017]. In contrast, Venegas et al. [-@venegas2019] found no association between
depth and the alleviation of heat stress across a range of shallow reefs in the Pacific.

This investigation supports the hypothesis that reefs at greater depths will exhibit
characteristics of refugia and prolonged resilience (in terms of coral cover) under climate
change compared to shallower reefs. Additionally, Liu, Callaghan and Baldock [-@liu2024]
suggest that rubble instability is inversely correlated with reef depth, possibly limiting
juvenile coral recruitment capacity of shallow reefs. A caveat to depth-resilience findings
is the quality of the bathymetry data used to calculate median reef depth. As detailed
previously, estimates of median reef depth are derived from satellite imagery (at 10m^2^
resolution) which can be subject to high degrees of uncertainty, both in terms of the
estimated depth for each pixel as well as their alignment to the established GBRMPA reef
outlines.

Current reef restoration and intervention efforts across the GBR, such as deployment of
coral seeding, coral fragment devices and Crown of Thorns Starfish control, target reefs
with sites in the 1-10m depth range [@howlett2021; @randall2021; @whitman2024]. While there
are no explicit justifications for this depth range, intervention depth is likely
constrained by snorkelling and diving deployment and monitoring logistical accessibility,
visual identification of sites from the surface, in combination with tourism return value.
Of the assessed reefs occurring within the 1-10m depth range (1551 reefs), 59% (920) of
reefs are consistently clustered into the Low and Medium cover clusters across the GCMs (at
the GBRMPA management region scale), with many found to be unable to maintain positive
carbonate budgets under projected conditions. PDA revealed a range of depths from 10-15m
where the probability of a reef being clustered into the High cover cluster increased
substantially compared to shallower depths. Considering this 10-15m depth range when
assessing possible intervention sites may reduce the exposure of planted and seeded corals
to high thermal stress, while still maintaining effective logistical access to sites.

It is a common conclusion in coral reef ecology that a primary facet of reef resilience is
the supply of recruits that a reef receives following disturbance [@hock2017; @mumby2008;
@torres2024]. No direct, first order, relationship between weighted incoming connectivity
and the ability of reefs to maintain positive carbonate budgets under future conditions was
found. There has been contrasting evidence [@bode2018; @hock2017] surrounding whether recent
generation connectivity modelling is able to identify reefs that are important for recovery
processes, with findings dependent on the larval connectivity model used. These
investigations were performed using prior generations of larval connectivity models
parameterised for 2008-2013 [@hock2017] and 1996-2002 [@bode2018] time periods, without
considering the influence of reef depth on resilience. Using updated 1km^2^ resolution
larval connectivity across the whole GBR, with a limited temporal sample of particle flows,
it was found that larval connectivity alone may not be important or reef resilience and
recovery but should be considered in combination with more influential factors such as
depth.

Findings on the importance of connectivity likely differ from literature due to the highly
uncertain nature of larval connectivity modelling [@choukroun2025; @vogt-vincent2023], the
way larval flows and juvenile recruitment are implemented in ADRIA - CoralBlox, and the
magnitude of early bleaching events decreasing the breeding capacity of strongly connected
reefs. Analysing daily connectivity data Vogt-Vincent et al. [-@vogt-vincent2023] suggest
that time-mean connectivity may not be suitable for capturing the seasonal - ecological time
scale connectivity between locations due to high daily variability in connectivity data.
Connectivity matrices used in this investigation have large relative standard deviations for
larval transition probabilities between reefs over the 24 days used
(@sfig-connectivity-rsd). Using alternative summarisation methods that capture
ecological-timescale patterns in coral larval dispersal, such as cumulated implicit
connectivity [@vogt-vincent2023], future investigations may find increased importance of
both depth and reef connectivity for resilience, in line with other investigations
[@hock2017; @torres2024]. Choukroun et al [-@choukroun2025] performed a comparison of three
GBR-scale connectivity models, including GBR1, and suggest the use of a model ensemble
approach to estimate larval dispersal due to the high sensitivity of connectivity
predictions to model specification. Further improvements and research in connectivity
modelling are necessary when incorporating connectivity as a supplementary factor in reef
resilience and intervention-planning analyses.

Under all GCMs many reefs are projected to suffer substantial declines in coral cover
relative to 2025 levels, with an average of 38% of reefs (924 reefs) clustered into the Low
cover cluster at the management area scale across GCMs. NorESM2-MM and ACCESS-ESM1-5 GCMs
convey the most coral cover maintenance into the future. Differences between Low, Medium and
High reef clusters in cover time series are most notable under these two GCMs
(@fig-gcm-cover-trajectories; @stbl-cluster-cid). Maintenance of coral cover into the future
is linked to the Equilibrium Climate Sensitivity of the GCM used as levels of future
recovery and timespan of cover maintenance increase as GCM ECS increases
(@fig-gcm-cover-trajectories). Under high-ECS GCMs (GFDL-CM4, EC-Earth3-Veg and ACCESS-CM2)
large declines and lower rates of recovery in high cover clusters are common compared to
lower-ECS GCMs.

Large differences in cover time series seen across the GCMs suggest it is important to
consider uncertainty in future conditions when assessing possible biological responses to
change. This is supported by recent literature suggesting an effective approach to capturing
climate change uncertainty is to model responses using GCMs separately [@shepherd2018].
Despite large differences in coral cover across GCMs, the patterns identified between low,
medium and high clusters of reefs suggest that the relative importance of environmental and
biological factors such as depth refugia, connectivity and surface DHW levels is consistent
across scenarios.

Reef managers may consider the potential for positive flow-on effects due to outgoing
connectivity when selecting intervention sites. The necessary connectivity data, however,
must first be available to provide a sufficient degree of confidence to support such site
selection decisions (compare the ongoing discussion in Mumby et al. [-@mumby2018], Bode et
al. [-@bode2018] and Choukroun et al. [-@choukroun2025]). Given connectivity is a transient,
and much more difficult, property to measure that is subject to comparatively higher sources
of uncertainty, depth may be a more reliable indicator of long-term resilience, particularly
where no further information is available.

## Limitations

There are multiple caveats in how coral ecosystem dynamics are modelled in this
investigation. Coral colonies are modelled as diameter values that increase over time
through growth. Additionally, the influence of light intensity on coral growth or the
negative influence of depth on coral growth rates due to reduced available light levels are
not modelled in this investigation [@baker1975; @huston1985; @ruiz-diaz2022]. If included in
this investigation, it is possible that reef recovery ability, via regrowth, would be
reduced at greater depths, reducing the positive effect of depth refugia for temporal
resilience. Additionally, reduced growth rates at increased depths may reduce carbonate
budget maintenance due to lower rates of CaCO~3~ accretion. Due to the availability of
quality future projected data this investigation does not consider other important impacts
such as waves, cyclones, ocean currents and Crown of Thorns Starfish (CoTS) on coral colony
survival and bleaching [@massel1993; @deaker2022].

Uncertainty in connectivity modelling outputs, satellite-derived bathymetry data and future
thermal stress projections likely influence the results obtained in this investigation.
While the resolution of connectivity data used in this investigation improves upon data used
in comparable studies [@bozec2025], the time-mean implementation used may not effectively
capture long term patterns [@vogt-vincent2023]. Using alternative connectivity
implementation methods that better capture the ecological-timescale trends in reef
connections rather than the high daily variability, would improve confidence in the
connectivity findings of this investigation [@vogt-vincent2023]. Increased samples to inform
baseline connectivity data, along with the derivation of connectivity from an ensemble of
biophysical models, would also improve confidence in connectivity data for ecological
modelling and management applications [@choukroun2025].

DHW data used in this investigation have not been bias corrected for the Great Barrier Reef
region and are part of a wider Australian dataset [@dixon2022] developed using statistical
downscaling. Lachs et al. [-@lachs2021] suggest the utility of DHW levels for prediction of
coral bleaching can be improved by reducing the threshold for HotSpot Anomaly values from
MMM +1 to MMM and reducing the accumulation window from 12 weeks to 8 weeks. The presented
analyses assessed a range of future climate responses, thermal projections and ecological
parameterisations of ADRIA-CoralBlox to account for many possible futures and suggests the
factors that influence reef resilience are consistent across these scenarios.

Highly accurate and precise estimates of reef depth across the GBR are currently not
possible to obtain with (publicly) available data. Data adopted for the given assessment are
said to be accurate up to 15m from Mean Sea Level [@GBRMPA2020; @li2021], however there are
many sources of uncertainty in the depth estimates used for this study. Satellite-derived
estimates are subject to different bottom types (rock, sand, seagrass, etc) and their effect
on reflectance, the water penetration depth of satellite sensors, influence of local
conditions (e.g., turbidity and wave activity), among many other factors. The median depths
for each indicative reef area were extracted from bathymetry data using zonal statistics and
depth values beyond the stated 15m accuracy threshold [@GBRMPA2020] were included. The
resulting depth estimates are therefore highly uncertain and are only adopted as a useful
indication for the purpose of the presented analysis. They are not intended to be accurate
and precise reef depths across the GBR.

In addition to the usual challenges of deriving data from satellite imagery, it is
acknowledged that there is high potential for misalignment between the bathymetry data and
GBRMPA reef outlines. Hammerton and Lawrey [-@hammerton2025], for example, identified 120
false positives, where features identified as reefs were sand banks or rocky reefs (rather
than coral reefs). Reefs with bathymetry data covering less than 5% of their indicative area
were excluded from analyses (see @sfig-depth-cutoff). Existing GBRMPA reef outlines were
adopted to align with other ongoing modelling and analyses conducted as part of the Reef
Restoration and Adaptation Program (<https://gbrrestoration.org>; [@thereef]).

The modelling conducted with ADRIA-CoralBlox itself is subject to many uncertainties. For
one, a formal mechanistic and spatial validation of the model represents an area for future
refinement and is the focus of a future publication. The consistency of projected patterns
with known coral-climate relationships and reef characteristics provides confidence in the
model's ability to meaningfully capture ecological signals at the GBR-scale. The mechanistic
basis of the model supports the robustness of these findings for understanding broad-scale
coral cover responses to climatic drivers. The aim here, however, was to assess the relative
influence of reef characteristics on reef resilience across a range of future conditions and
parameterisations, rather than provide spatially explicit and precise predictions of reef
outcomes. Using this approach, results suggest reef depth is an important factor for reef
resilience under thermal stress.

Improvements in remote sensing approaches for broad scale bathymetry measurement and
understanding of how depth impacts experienced thermal stress on reefs will further enhance
investigations of depth as a critical factor for reef resilience. Additional analyses could
build on the findings of this study by assessing the impacts of prioritising reef depth for
reef intervention decision outcomes. Future analyses could incorporate other environmental
and ecological stressors such as wave activity, ocean acidification, and Crown-of-Thorn
Starfish [@lin2023; @mcclanahan2005; @grimaldi2023; @grimaldi2022; @liu2024; @eyre2018].

## Conclusion

The results presented suggest that when modelled as part of a large and complex ecosystem,
reef depth is a key factor contributing to ongoing reef resilience. This investigation
provides evidence in support of depth as a form of thermal refugia for shallow-water reefs
on the GBR. Targeting reefs with median depths greater than 10m may aid in identifying the
most resilient reefs under climate change. Further analyses that investigate the benefits of
incorporating depth-based resilience into reef intervention decision making, as well as
further research and development in connectivity modelling methods for whole-ecosystem
scales are recommended.

# Acknowledgements

The authors acknowledge the Traditional Owners of the Sea Country on which the modelling was
conducted for. The authors additionally acknowledge the Bindal, Jagera, and Ngunnawal
Peoples, the lands on which the authors conducted the model development, analysis, and
writing. The authors also acknowledge the contributions of Barbara Robson and Jessica
Benthuysen for comments provided early in the manuscript preparation. The authors would like
to additionally acknowledge and thank Shaun Wilson and Juan Carlos Ortiz for discussions
around carbonate budget thresholds.

This research was funded by the Reef Restoration and Adaptation Program and facilitated by
the Australian Institute of Marine Science. The authors acknowledge thermal projection data
sourced from HighResCoralStress datasets, model parameterisation data sourced from the
Ecological Intelligence for Reef Restoration (EcoRRAP) subprogram, larval transition
probability data derived from the eReefs GBR1 hydrodynamic model, and spatial and depth data
available from the Great Barrier Reef Marine Park Authority. The eReefs Project is a
public-private collaboration between Australia’s leading operational and scientific research
agencies, government, and corporate Australia.

# References

::: {#refs}
:::

# Author Contributions

**Benjamin Grier:** conceptualisation, data curation, formal analysis, investigation,
methodology, visualization, writing – original draft, writing – review and editing. **Takuya
Iwanaga:** conceptualisation, data curation, formal analysis, investigation, methodology,
visualization, writing – original draft, writing – review and editing. **Pedro Ribeiro de
Almeida:** data curation, model development, analysis, writing - methodology, writing -
review and editing, visualisation. **Chinenye Ani:** data curation, writing - methodology,
writing - review and editing. **Sam Matthews:** Writing - review and editing.

# Conflict of Interest Statement

The authors declare no conflicts of interest.

# Data Availability Statement

The full reproducible investigation, and links to required data sources, can be found at
Grier and Iwanaga [-@grier2025].

# Supplementary Material

![Equilibrium Climate Sensitivity (ECS) values in °C for the GCMs selected (point values).
The pink - dashed box represents the high-certainty ‘very likely’ range for ECS values and
the solid red box represents low-certainty ‘likely’ range for ECS values (Forster et al.,
2021).](../figs/ecs_plot.png){#sfig-ecs fig-align="center" width="10cm"}

![Distribution of GBRMPA [-@GBRMPA2020] satellite derived depth data coverage levels across
3806 possible reefs. Reefs below the 5% data coverage threshold (represented by the red
vertical line) were removed from the
investigation.](../figs/reef_depth_included_cutoff.png){#sfig-depth-cutoff
fig-align="center" width="14.8cm" height="9.5cm"}

![Reef Degree Heating Week time series clustered within each management area, for each GCM
analysed. Time series were clustered based on their behaviour between 2030 and 2060. Time
series with comparatively low median area-relative cover is indicated in green, intermediate
cover in orange, and high in blue. Solid lines represent the cluster median time series and
bands represent the 2.5 to 97.5 percentile confidence intervals. Each management area is
represented five times (for each GCM), with each GCM displayed
horizontally.](../figs/GCM_dhw_timeseries_plot.png){#sfig-gcm-dhw-trajectories
fig-align="center" width="14.82cm"}

::: {#stbl-metrics}
| Metric | Used in | Definition | Justification |
|-----------------------|-----------------------|-----------------------|-----------------------|
| Percentage coral cover time series | Time series clustering, Carbonate budget analysis | Total coral cover as a percentage of reef area | To summarise coral population health over time. |
| Median depth | Time series cluster assessment Carbonate budget analysis | Reef median depth as calculated with zonal raster analysis | Depth is a critical form of environmental refugia from high thermal stress |
| Mean time series DHW | Time series cluster assessment | Reef mean DHW value across time series | To quantify the surface thermal stress experienced on each reef over time series. |
| Source - to - sink connectivity ratio | Time series cluster assessment | Ratio of reef outgoing to incoming connectivity | To examine whether a reef may be a 'net contributor' or 'net receiver' of larvae in the connectivity network. |
| Weighted incoming connectivity | Time series cluster assessment, Carbonate budget analysis | Incoming connectivity strength weighted by mean time series coral cover of source reefs | To approximate the larval flow received by a reef over the projected time series. |
| Outgoing connectivity strength | Time series cluster assessment, Carbonate budget analysis | Sum of a reef's outgoing larval transition probability values. | To understand the contribution of a reef to the connectivity network and the possibility for flow-on effects from reef states. |
| Larval retention probability | Time series cluster assessment | Diagonal larval transition matrix values. | To understand the relative proportion of larvae retained on a reef. |
| Carrying capacity | Time series cluster assessment | Reef habitable area \[m^2^\] | Captures the size of the viable reef extent. |

Quantitative metrics used in this investigation.
:::

```{julia}
#| echo: false
#| warning: false
#| message: false
#| output: asis

cap = """
Complexity invariant distance (CID) between low and high cluster median time series in each management area under each GCM. CID values are calculated for percentage cover time series (@fig-gcm-cover-trajectories) and Degree Heating Week (DHW) time series (@sfig-gcm-dhw-trajectories). Complexity invariant distance represents the Euclidean distance between time series, corrected by the complexity of the two time series. CID values are used to quantify overall differences between these two cluster levels at management area and GCM levels. CID values for percentage cover and DHW time series are not directly comparable as the time series use different units.
"""
using Markdown,Tables,MarkdownTables
cd("../src")
include("../src/ADRIA/HighResCoralStress/6_quantifying_cluster_differences.jl"); # Quantify low-high cluster differences using CID metric.
rename!(distances,
    "management_area" => "Management area",
    "CID_cover" => "CID - cover",
    "CID_dhw" => "CID - DHW"
)
print("""
::: {.table #stbl-cluster-cid}
$(markdown_table(distances, String))

$(cap)
:::
""")
```

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by management area scale cluster assignment.
Colour-coded areas outline GBR marine park management regions, where orange represents the
Far Northern management region, green represents Cairns/Cooktown, red covers
Townsville/Whitsunday and blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids are
marked individually for visual clarity. Reefs that do not have a consistent cluster
assignment level across all GCMs at mangement area scale are coloured grey. All consistently
clustered reefs are coloured according to their management area scale cluster assignment.
Green represents reefs in the low cover cluster, orange represents reefs in the medium cover
cluster and blue represents reefs in the high cover cluster. All 2197 reefs included in this
investigation are represented in this figure. Annotations represent major coastal
settlements along the GBR.](../figs/gcm_cluster_assignment_map.png){#sfig-gcm-cluster-map
fig-align="center" width="14.82cm"}

![Heatmaps indicating reef cluster assignments within each bioregion across the five GCMs.
Green indicates a low cover cluster assignment, orange represents a medium cover assignment
and blue represents assignment of a reef to a high coral cover cluster. The vertical width
of reef elements varies depending on the number of reefs within the bioregion (displayed on
the y axis). The x axis represents the different GCM levels (EC-Earth3-Veg, ACCESS-ESM1-5,
ACCESS-CM2, NorESM2-MM and
GFDL-CM4).](../figs/GCM_bioregion_cluster_assignments.png){#sfig-gcm-bioregion-cluster-assignment
fig-align="center" width="14.82cm"}

![Partial dependence plot indicating the probability of cluster assignment along interacting
values of median reef depth (meters) and log10 weighted outgoing connectivity. Colour
indicates the probability of assignment to each cluster, with lighter colours indicating
higher probability of assignment. Panel A shows the probability of assignment for the Low
cover cluster, Panel B shows Medium cover cluster and Panel C shows assignment probability
for the High cover cluster. Probability values for each cluster are generated by the random
forest classifier using each combination of depth and weighted outgoing connectivity values
along the axes at 50 grid points. The actual distributions of depth and outgoing
connectivity values for reefs are displayed in panels D and E
respectively.](../figs/ts_cluster_rf_twoway_depth_outgoingconn_pdp.png){#sfig-ts-cluster-pdp-twoway-outgoing
fig-align="center" width="14.82cm"}

![Scatter plots indicating the bioregion test-prediction accuracy (proportion of reefs in
each bioregion assigned correct clusters) from the Random Forest model. Plot panels
represent the bioregion accuracy across various predictor ranges and bioregion attributes,
such as mean bioregion depth, carrying capacity, DHW value, total connectivity strength,
Source-to-sink ratio and the number of reefs in each
bioregion.](../figs/rf_performance_across_predictors.png){#sfig-rf-predictor-perf
fig-align="center" width="14.82cm"}

![Heatmap indicating reef connectivity relative standard deviation (RSD %). Reef
connectivity relative standard deviation represents the reef standard deviation connection
strength as a percentage of reef mean connection strength. Lighter colours indicate higher
RSD % values.](../figs/connectivity_rsd_percent.png){#sfig-connectivity-rsd
fig-align="center" width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by median reef depth. Colour-coded areas outline GBR
marine park management regions, where orange represents the Far Northern management region,
green represents Cairns/Cooktown, red covers Townsville/Whitsunday and blue covers
Mackay/Capricorn [@GBRMPA2007]. Reef centroids are marked individually for visual clarity.
Darker colours represent greater reef depth values than lighter colours. All 2197 reefs
included in this investigation are represented in this figure. Annotations represent major
coastal settlements along the GBR.](../figs/depth_med_input_map.png){#sfig-depth-map
fig-align="center" width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by reef carrying capacity (coral habitable area).
Colour-coded areas outline GBR marine park management regions, where orange represents the
Far Northern management region, green represents Cairns/Cooktown, red covers
Townsville/Whitsunday and blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids are
marked individually for visual clarity. Darker colours represent greater carrying capacity
area values than lighter colours. All 2197 reefs included in this investigation are
represented in this figure. Annotations represent major coastal settlements along the
GBR.](../figs/abs_k_area_input_map.png){#sfig-abs-k-area-map fig-align="center"
width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by outgoing connection strength (log10). Colour-coded
areas outline GBR marine park management regions, where orange represents the Far Northern
management region, green represents Cairns/Cooktown, red covers Townsville/Whitsunday and
blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids are marked individually for
visual clarity. Darker colours represent higher outgoing connection strength values than
lighter colours. All 2197 reefs included in this investigation are represented in this
figure. Annotations represent major coastal settlements along the
GBR.](../figs/log_out_strength_input_map.png){#sfig-outgoing-conn-map fig-align="center"
width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by source-to-sink connectivity ratio (log10).
Colour-coded areas outline GBR marine park management regions, where orange represents the
Far Northern management region, green represents Cairns/Cooktown, red covers
Townsville/Whitsunday and blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids are
marked individually for visual clarity. Darker colours represent higher source-to-sink
values than lighter colours. Source-to-sink ratio values above zero (one on normal scale)
indicate a reef has greater outgoing than incoming connectivity. All 2197 reefs included in
this investigation are represented in this figure. Annotations represent major coastal
settlements along the GBR.](../figs/log_so_to_si_input_map.png){#sfig-sotosi-conn-map
fig-align="center" width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by larval retention probability (log10). Colour-coded
areas outline GBR marine park management regions, where orange represents the Far Northern
management region, green represents Cairns/Cooktown, red covers Townsville/Whitsunday and
blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids are marked individually for
visual clarity. Darker colours represent higher probability of retaining spawned larvae than
lighter colours. All 2197 reefs included in this investigation are represented in this
figure. Annotations represent major coastal settlements along the
GBR.](../figs/log_self_strength_input_map.png){#sfig-self-conn-map fig-align="center"
width="14.82cm"}

## Degree Heating Week data processing

Monthly mean SST climatological baselines, for each 1km^2^ pixel, were calculated from the
daily SST data following NOAA methodology [@liu2017; @skirving2020]. For each pixel of SST
data, the Monthly Mean SST climatology was calculated by computing the mean SST value for
each calendar month (January through December) across the 28-year baseline period from 1985
to 2012. For each month separately, this climatological baseline was adjusted to centre at
year 1988.2857, which attempts to account for any long-term trends within the baseline years
themselves (see Skirving et al. [@skirving2020]). The adjustment ensures that the
climatology represents conditions at a specific temporal reference point rather than being
influenced by gradual warming or cooling trends that may have occurred during the 1985-2012
period. The resulting monthly climatologies serve as a standardized reference against which
current SST conditions can be compared to identify thermal anomalies and assess coral
bleaching risk, following the methodology established by Skirving et al. [-@skirving2020].

Degree Heating Weeks (DHWs) were derived using the "HotSpot SST Anomaly" approach
[@skirving2020]. The "HotSpot SST Anomaly" represents thermal stress experienced by coral
reefs and is calculated as the difference between daily SST values and the maximum of a
pixel's monthly mean climatology across all twelve months (i.e., the maximum monthly mean
SST). This approach uses the annual maximum temperature as the baseline because corals are
adapted to withstand their local warmest conditions under normal seasonal cycles. When
temperatures exceed this seasonal maximum, corals experience thermal stress that can lead to
bleaching. Only positive anomalies, greater than 1°C, are considered relevant for coral
stress, as temperatures below the seasonal maximum do not contribute to bleaching risk.

## ADRIA-CoralBlox

The CoralBlox model incorporates linear extension (growth) and background mortality rates
that are dependent on the size and functional group of a coral colony. Environmental
disturbances and reproduction are not directly considered within CoralBlox, and are instead
provided by the ADRIA (Adaptive Dynamic Reef Intervention Algorithms) platform
[@iwanaga2023]. Within ADRIA, coral life history and environmental events are implemented in
the following order: coral colony growth; coral reproduction; larval connectivity and
settlement; and coral bleaching due to heat stress.

Coral fecundity rates are dependent on colony size and functional group following the
results of Hall & Hughes [-@hall1996]. Coral fertilization rates are not considered within
this model, however larval survival and viability are incorporated in connectivity modelling
(see Connectivity modelling). Viable larvae settle at a reef location and are incorporated
into the model as the smallest size class but are not directly impacted by modelled
bleaching mortality. There has been contrasting evidence for juvenile corals being immune to
thermal bleaching events [@depczynski2013], it is assumed the high background mortality of
juveniles includes thermal stress [@álvarez-noriega2018].

### Model implementation

ADRIA-CoralBlox implements five functional groups common to the GBR, tabular Acropora,
corymbose Acropora, corymbose non-Acropora, small massives and large massives. CoralBlox
uses user-defined size classes that influence size-dependent growth and mortality rates,
through which the coral colonies progress as they grow in diameter. Size classes were
initially informed by Bozec et al. [-@bozec2022].

The area of each coral colony is tracked in CoralBlox by the area of a circumference. A
coral population is then represented by a discretised distribution of $p(x)$ coral
diameters, composed of smaller uniform distributions, each representing the number of corals
within a certain diameter range:

$$
\rho(x) =
\begin{cases}
\lambda_1, & d_0 < x < d_1 \\
\vdots & \vdots \\
\lambda_N, & d_{N-1} < x < d_N \\
0, & x \notin [d_0, d_N]
\end{cases}
$$

where $N$ represents the number of intervals used to discretise $p(x)$, and $d_0$ and $d_N$
are the diameters of the smallest and biggest coral colonies, in that order. The coral cover
for the entire population is given by:

$$
\begin{aligned}
C &= \int_{d_0}^{d_N} \pi x^2 \rho(x) \, dx \\
  &= \sum_{n=1}^{N} \pi \lambda_n \int_{d_{n-1}}^{d_n} x^2 \, dx \\
  &= \sum_{n=1}^{N} \pi \lambda_n \left( \frac{d_n^3 - d_{n-1}^3}{3} \right)
\end{aligned}
$$

These are uniform distributions that compose $p(x)$, a coral block characteristed by a
diameter density $\lambda_n$ (the block's height) and a diameter range $[d_{n-1},d_n]$ (the
base of the block). Therefore, instead of working with a continuous diameter's distribution,
CoralBlox updates each coral block separately. A mortality event is modelled as a decrease
in a coral block's density, and a growth event as an increase in a coral block's diameter
range limits. Both growth and mortality rates are size class dependent, which means the same
growth and mortality rates are used for blocks within a size class. @sfig-coralblox-example
shows a model's behaviour under low disturbance and no interventions.

![Time series comparing modelled and observed relative coral cover for Ben reef showing a
recovery process under very low disturbance and no interventions. The observed data used
here is from the AIMS Long-Term Monitoring Program (LTMP) . Error metrics including Root
Mean Square Error (0.06) and the Spearman Rank Correlation Coefficient (0.9) is also shown.
The second plot shows the DHW and Cyclone or COTS events. The third plot shows the benthic
composition for each functional group as a proportion of the reef’s cover at each
year.](../figs/coralblox_reef_example.png){#sfig-coralblox-example width fig-align="center"
width="14.82cm"}

In ADRIA we track the thermal tolerance of each functional group and size class as a
truncated normal distribution that is updated in each timestep following growth and
recruitment. This distribution determines the proportion of the population on a reef that is
susceptible to bleaching (i.e. has a thermal threshold below the experienced DHW value).
Starting distributions for thermal tolerance levels are informed by Bairos-Novak et al.
[-@bairos-novak2021] and expert opinion, and are additionally varied in the scenario
exploration.

### Scenario generation

Scenarios were sampled from the range of environmental and ecological factors using the
low-discrepancy Sobol' sampling method [@sobol1967; @sobol1993] with Owen scrambling
[@owen1995]. A base of 2 and padding of 32 is used for the Owen scrambling. Ecological
factors were sampled using a +/- 10% range relative to their nominal (assumed best guess)
value.

### Sensitivity analysis

A global sensitivity analysis was performed using Shapley Effects [@goda2021] implemented in
the SAShE.jl package [@ribeirodealmeida2025a]. For this analysis, 10,000 samples were
simulated for a single reef and timestep. Two metrics were considered, difference in coral
cover and difference in evenness. The factors analysed were heritability, mean colony
diameter, linear extension, mortality base rate, mean and standard deviation of the
tolerance distribution, linear extension scale factor, mortality rate scale factor reef
habitable area, reef depth, DHW, and initial coral cover. @sfig-coralblox-sa shows the
result of such analysis for different ranges of DHW. In both cases a similar effect takes
place: when DHW = 0, initial cover is the most influential factor then, when DHW \> 0, depth
and DHW start to appear as influential factors and, as DHW values get higher, depth becomes
more influential in detriment of DHW.

![Parametric sensitivity analysis conducted with Shapley effects. Each column reflects
sampling of different DHW ranges. The first column represents model runs with DHW = 0, and
the remaining columns represent models runs with DHW valued between 0 and 8, 8 and 16, 16
and 30, and 0 and 30. The first row shows the Shapley effect for change in coral cover and
the second for change in evenness of species
abundance.](../figs/coralblox_sens_analysis.png){#sfig-coralblox-sa width fig-align="center"
width="14.82cm"}

### Time series clustering

The CID time series clustering metric corrects the Euclidean distance between pairs of time
series with their relative complexity (which is the quotient of their variability). This is
to ensure reefs are clustered based on their underlying temporal dynamics rather than
aggregating the coral cover across all timesteps. The process creates a $n * n$ distance
matrix (where $n$ is the number of time series in the group) that is used as an input to a
k-medoids clustering algorithm [cf. @steinmann2020]. The three reef clusters are labelled
with qualitative-ordered labels from Low, Medium and High based on their median cover
relative to each other cluster over the 2030-2060 period. The selected time frame prevents
the classification from being overly influenced by any steep declines in the initial years
of simulations and avoids the post-2060 time period where reefs are projected to be under
severe stress and in a declined state [@bozec2025].

## ACCESS-ESM1-5 results

ACCESS-ESM1-5 was selected for GCM-level results as an intermediate severity GCM, with an
ECS value closest to the midpoint of the IPCC likely range of ECS values (3.87 °C). The
following section includes supplemental results for analyses under this GCM. A comparison of
results across GCMs can be found in the main text, and individual GCM-level results for
other GCMs can be found at Grier and Iwanaga [-@grier2025].

![Bar plot indicating the Spearman's rank correlation values for the number of years above
carbonate budget threshold ($theta$) and, median reef depth and log10 weighted incoming
connectivity values. Depth correlation values are displayed in the left plot, while
connectivity correlation values are displayed in the right plot. Displays results for
ACCESS-ESM1-5
GCM.](../figs/ACCESS-ESM1-5/depth_conn_carbonate_correlations.png){#sfig-access-esm1-5-carb-budget-corr
fig-align="center" width="14.82cm"}

![Scatter plot indicating reef median depth (metres) and log10 weighted incoming
connectivity for each reef. Point colours represent the median number of years each reef
maintains positive carbonate budgets across $theta$ values from 10-20% live coral cover.
Displays results for ACCESS-ESM1-5
GCM.](../figs/ACCESS-ESM1-5/depth_conn_mean_carbonate_budget.png){#sfig-access-esm1-5-mean-carb-budget
fig-align="center" width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by median number of years exceeding positive carbonate
budget threshold. Colour-coded areas outline GBR marine park management regions, where
orange represents the Far Northern management region, green represents Cairns/Cooktown, red
covers Townsville/Whitsunday and blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids
are marked individually for visual clarity. Reefs that have a median positive carbonate
budget year value of 0 years are coloured in grey. All other reefs are coloured according to
their median years across threshold values, with darker colours representing greater number
of years with positive carbonate budgets than lighter colours. All 2197 reefs included in
this investigation are represented in this figure. This map depicts values from the
ACCESS-ESM1-5 GCM. Annotations represent major coastal settlements along the
GBR.](../figs/ACCESS-ESM1-5/median_carbonate_budget_map.png){#sfig-carb-budget-map
fig-align="center" width="14.82cm"}

### Bioregion scale clustering

The following section includes bioregion scale clustering results, full results for other
spatial scales (management area and GBR) can be found at Grier and Iwanaga [-@grier2025].
Results are only shown and discussed for ACCESS-ESM1-5, an intermediate ECS scenario
(@sfig-ecs). Those interested in results for the other assessed GCMs are referred to Grier
and Iwanaga [-@grier2025]. Reefs in the High cluster were consistently found to have the
greatest median reef depths across bioregions (@sfig-access-esm1-5-bioregion-depth). Across
bioregions, there were no consistent patterns between reef clusters in mean DHW values
(@sfig-access-esm1-5-bioregion-dhwmean), log10-weighted incoming connectivity
(@sfig-access-esm1-5-bioregion-weightedincoming), log10 outgoing connection strength
(@sfig-access-esm1-5-bioregion-outgoingconn), log10 source-to-sink connectivity ratio
(@sfig-access-esm1-5-bioregion-logsosi) and log10 larval retention probability
(@sfig-access-esm1-5-bioregion-selfconn). Across six of the 29 bioregions reefs in the high
cover cluster have lower log10 carrying capacity values than reefs in other clusters
(@sfig-access-esm1-5-bioregion-carrying-capacity).

![Reef area-relative coral cover time series clustered within each bioregion. Time series
were clustered based on their behaviour between 2030 and 2060. Time series with
comparatively low median area-relative cover is indicated in green, intermediate cover in
orange, and high in blue. Solid lines represent the cluster median time series and bands
represent the 95th percentile confidence intervals. Displays results for ACCESS-ESM1-5
GCM.](../figs/ACCESS-ESM1-5/bioregion/bioregion_cover_timeseries.png){#sfig-access-esm1-5-bioregion-timeseries
fig-align="center" width="14.82cm"}

![Median depth for reefs within each bioregion under ACCESS-ESM1-5, separated into clusters
assigned by time series clustering. Time series were clustered based on their behaviour
between 2030 and 2060. Time series with comparatively low median area-relative cover is
indicated in green, intermediate cover in orange, and high in blue. Solid lines represent
the median depth for each cluster across reefs and bands represent the distribution of depth
values within each
cluster.](../figs/ACCESS-ESM1-5/bioregion/depth_bioregion_violin.png){#sfig-access-esm1-5-bioregion-depth
fig-align="center" width="14.82cm"}

![Mean time series DHW values for reefs within each bioregion, separated into clusters
assigned by time series clustering, under ACCESS-ESM1-5. Time series were clustered based on
their behaviour between 2030 and 2060. Time series with comparatively low median
area-relative cover is indicated in green, intermediate cover in orange, and high in blue.
Solid lines represent the median DHW level for each cluster and bands represent the
distribution of mean DHW levels within each
cluster.](../figs/ACCESS-ESM1-5/bioregion/mean_dhw_bioregion_violin.png){#sfig-access-esm1-5-bioregion-dhwmean
fig-align="center" width="14.82cm"}

![Reef carrying capacity (coral habitable area, in base-10 log scale) for reefs within each
bioregion, separated into clusters assigned by time series clustering, under ACCESS-ESM1-5.
Time series were clustered based on their behaviour between 2030 and 2060. Time series with
comparatively low median area-relative cover is indicated in green, intermediate cover in
orange, and high in blue. Solid lines represent the median carrying capacity for each
cluster and bands represent the distribution of values within each
cluster.](../figs/ACCESS-ESM1-5/bioregion/carrying_capacity_bioregion_violin.png){#sfig-access-esm1-5-bioregion-carrying-capacity
fig-align="center" width="14.82cm"}

![Source-to-sink connectivity ratios (in base-10 log scale) for reefs within each bioregion,
separated into clusters assigned by time series clustering, under ACCESS-ESM1-5. Time series
were clustered based on their behaviour between 2030 and 2060. Time series with
comparatively low median area-relative cover is indicated in green, intermediate cover in
orange, and high in blue. Solid lines within each violin represent the median source-to-sink
ratio for each cluster and bands represent the distribution of source-to-sink ratios within
each cluster. The vertical grey line represent a source-to-sink ratio of 0 (in base-10 log
scale) indicating equal outgoing and incoming connectivity
levels.](../figs/ACCESS-ESM1-5/bioregion/so_to_si_bioregion_violin.png){#sfig-access-esm1-5-bioregion-logsosi
fig-align="center" width="14.82cm"}

![Weighted incoming connectivity (in base-10 log scale) for reefs within each bioregion,
separated into clusters assigned by time series clustering, under ACCESS-ESM1-5. Time series
were clustered based on their behaviour between 2030 and 2060. Time series with
comparatively low median area-relative cover is indicated in green, intermediate cover in
orange, and high in blue. Solid lines within each violin represent the median base-10 log of
weighted incoming connectivity for each cluster and bands represent the distribution of
connectivity values within each
cluster.](../figs/ACCESS-ESM1-5/bioregion/weighted_incoming_conn_bioregion_violin.png){#sfig-access-esm1-5-bioregion-weightedincoming
fig-align="center" width="14.82cm"}

![Outgoing connection strength (in base-10 log scale) for reefs within each bioregion,
separated into clusters assigned by time series clustering, under ACCESS-ESM1-5. Time series
were clustered based on their behaviour between 2030 and 2060. Time series with
comparatively low median area-relative cover is indicated in green, intermediate cover in
orange, and high in blue. Solid lines within each violin represent the median base-10 log of
outgoing connection strength for each cluster and bands represent the distribution of
connectivity values within each
cluster.](../figs/ACCESS-ESM1-5/bioregion/outgoing_strength_bioregion_violin.png){#sfig-access-esm1-5-bioregion-outgoingconn
fig-align="center" width="14.82cm"}

![Larval retention probability (in base-10 log scale) for reefs within each bioregion,
separated into clusters assigned by time series clustering, under ACCESS-ESM1-5. Time series
were clustered based on their behaviour between 2030 and 2060. Time series with
comparatively low median area-relative cover is indicated in green, intermediate cover in
orange, and high in blue. Solid lines within each violin represent the median base-10 log of
larval retention probability for each cluster and bands represent the distribution of
probability values within each
cluster.](../figs/ACCESS-ESM1-5/bioregion/self_conn_bioregion_violin.png){#sfig-access-esm1-5-bioregion-selfconn
fig-align="center" width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by mean time series DHW value under ACCESS-ESM1-5.
Colour-coded areas outline GBR marine park management regions, where orange represents the
Far Northern management region, green represents Cairns/Cooktown, red covers
Townsville/Whitsunday and blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids are
marked individually for visual clarity. Darker colours represent higher mean DHW values than
lighter colours. All 2197 reefs included in this investigation are represented in this
figure. Annotations represent major coastal settlements along the
GBR.](../figs/ACCESS-ESM1-5/mean_dhw_input_map.png){#sfig-mean-dhw-map fig-align="center"
width="14.82cm"}

![Map of the Great Barrier Reef region, including GBRMPA management areas (polygons) and all
considered reefs (points), coloured by weighted incoming connectivity levels (Log10) under
ACCESS-ESM1-5. Colour-coded areas outline GBR marine park management regions, where orange
represents the Far Northern management region, green represents Cairns/Cooktown, red covers
Townsville/Whitsunday and blue covers Mackay/Capricorn [@GBRMPA2007]. Reef centroids are
marked individually for visual clarity. Darker colours represent higher weighted incoming
connectivity values than lighter colours. All 2197 reefs included in this investigation are
represented in this figure. Annotations represent major coastal settlements along the
GBR.](../figs/ACCESS-ESM1-5/weighted_incoming_conn_input_map.png){#sfig-incoming-conn-map
fig-align="center" width="14.82cm"}

## Random Forest Performance

::: {#stbl-confusion-matrix}
|               |         | **Ground Truth** |          |
|---------------|---------|------------------|----------|
| **Predicted** | **Low** | **Medium**       | **High** |
| **Low**       | 1371    | 682              | 151      |
| **Medium**    | 247     | 603              | 340      |
| **High**      | 97      | 302              | 787      |

Confusion matrix for the Random Forest classifier used to assess partial dependence.
Diagonals indicate correctly classified time series clusters. Columns are the "true" cluster
memberships and indicate the samples that were correctly or incorrectly classified as
Low/Medium/High. For example, the first column shows the number of samples correctly
classified into the Low cluster, and the number of Low samples incorrectly classified as
being in either the Medium or High coral cover clusters. There were 4580 samples used for
testing.
:::

::: {#stbl-rf-cluster-performance}
|                  | **Low** | **Medium** | **High** |
|------------------|---------|------------|----------|
| **Test samples** | 1715    | 1587       | 1278     |
| **Precision**    | 0.622   | 0.507      | 0.664    |
| **Recall**       | 0.799   | 0.38       | 0.616    |
| **F1**           | 0.7     | 0.434      | 0.639    |

Performance metrics for the Random Forest classifier for each of the time series clusters.
:::